#!/bin/sh /etc/rc.common

START=99
STOP=15
USE_PROCD=1

PROG=/usr/bin/lucky
DEFAULT_PRO_CONF='/etc/config/lucky.daji'

get_config() {
    config_get_bool enabled "$1" enabled 0
    config_get PRO_CONF "$1" configdir "$DEFAULT_PRO_CONF"
}

start_service() {
    config_load lucky
    config_foreach get_config lucky
    
    [ "$enabled" = "1" ] || return 1
    [ -d "$PRO_CONF" ] || mkdir -p "$PRO_CONF"
    
    procd_open_instance
    procd_set_param command "$PROG" -cd "$PRO_CONF"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger lucky
}
